### ISSUE TITLE
ENFO User Search should be case insensitive

### ISSUE THREAD

**Issue by patdnr** [gaepdit/enforcement-orders#93]
The search function is currently case sensitive when searching for the first or last name.

![image](https://user-images.githubusercontent.com/113926513/202955009-203e70a7-ea5f-48ec-a6fd-1d19fc262dbe.png)

![image](https://user-images.githubusercontent.com/113926513/202955040-bbc82479-facd-443c-908a-a4581b294f20.png)

**Comment by dougwaldron** [comment]
Case-sensitivity is database-platform specific.
